# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-03 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0002_auto_20201103_0659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='business_name',
            new_name='name',
        ),
    ]
