# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-03 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0003_auto_20201103_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='health_cont',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='police_cont',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
