# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-03 08:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0004_auto_20201103_0740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborhood',
            name='country',
        ),
    ]
